# This file was generated by GoReleaser. DO NOT EDIT.
cask "yara" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f4198db4011f3e4cd7ee2312dffd3bf28f15399beffc7a40dd850f63e49176a5"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a61073da986c41a051455222b528bbdce3c5991899eb8171e32dcf21c19152ca"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "184264edd659c17d6c24d4a7790bf6a66b0c4e1ce6875a1aa21f0a920855e4c9"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8725cf127ed202f2cb951abbb54ef5a67bbe1c3fe9f32b32fe2fcf9a147a719a"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yara"
  desc "Autonomous AI coding loop, powered by Claude Code"
  homepage "https://github.com/Elsayed91/yara"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yara"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yara"]
    end
  end

  # No zap stanza required

end
