# This file was generated by GoReleaser. DO NOT EDIT.
cask "yara" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0550e47fc24d2ceb7a7070c7a2db89e815a0089989c27292299408a5ec835127"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c8bc68d3944387597fbb02de7aac2f2ba8e9f9219538464dcacf1b4c922c149c"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2295943b1b4f32f40dc523c428d93fe1ee9fe7207651164bd7ba2afb112ad1d2"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e17e6d62282f695066012aedf534225903aae1ffd23c1354bb818038fba10c95"
      url "https://github.com/Elsayed91/yara/releases/download/v#{version}/yara_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yara"
  desc "Autonomous AI coding loop, powered by Claude Code"
  homepage "https://github.com/Elsayed91/yara"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yara"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yara"]
    end
  end

  # No zap stanza required

end
